### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by sinelaw**
- add stack.yaml
- replace terrible error message with less-than-terrible error message

### CODE REVIEW

**Comment by ElastiLotem** [comment]
Cool! Thanks for this :) Can you fix the little align/indent issue and then I'll merge?

**Comment by sinelaw** [comment]
Done, PR updated

**Comment by sinelaw** [comment]
MERGE MEEEEEEEE

**Comment by sinelaw** [comment]
bumping :) merge it! just got the annoying pattern match error again...

**Comment by ElastiLotem** [comment]
Merged, thanks.

**Comment by sinelaw** [comment]
You may want to bump the version? (If you upload to hackage?)

**Comment by ElastiLotem** [comment]
Done: http://hackage.haskell.org/package/resolve-trivial-conflicts-0.3.1.2

**Pull request closed without merging**
